### ISSUE TITLE
Unit is not defined

### ISSUE THREAD

**Issue by alfirin** [Azure/IoTPlugandPlay#39]
Hello the data type `Unit` is not defined.

There are some exemples here and there but no specification.
Please provide this.

Thanks a lot.

**Comment by askpatrickw** [comment]
I wonder if `unit` was replaced with `displayUnit` and the docs are just incorrect.

**Comment by askpatrickw** [comment]
see also #23

**Comment by askpatrickw** [comment]
Actually... I'm going to change my opinion on this...

Since "C" is the common abbreviation in science for Celsius, then Unit would be C, but the displayUnit could then be:
```
{
  "en": "Celsius",
  "hr": Celzijus,
  "ar": "مئوية"
}
```

Where the first example is English, the second Croatian and the third is Arabic.
So UNIT is going to dependent on your device data and the standard format for that unit in your industry\country\etc. 
Examples of Unit would be every kind of unit possible in science and industry which can be expressed using the support dataTypes of the DTDL.

**Comment by briancr-ms** [comment]
In an upcoming update we will clarify the unit property and the Unit type. I'll be interested to hear your feedback.

**Comment by askpatrickw** [comment]
Man when I worked at MSFT we had to provide the fix before closing bugs... so cushy nowadays. (that's a joke.) ;-)

Looking forward to hearing more.
